version: "3.9"

services:
  nginx:
    image: nginx:1.25-alpine
    container_name: midnight-explorer-web-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/letsencrypt
      - ./nginx/www:/var/www/certbot
    networks:
      - midnight-net

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/certs:/etc/letsencrypt
      - ./nginx/www:/var/www/certbot
    entrypoint: sh -c "trap exit TERM; while :; do sleep 12h & wait $${!}; done"

networks:
  midnight-net:
    external: true